### ISSUE TITLE
LabNex crashes

### ISSUE THREAD

**Issue by Cwpute** [labnex/LabNex#14] opened 2024-10-06 08:05 UTC
**I confirm that I have searched the issue tracker**
Before opening an issue, take a few minutes to search the issue tracker (both open and closed issues) for the problem you are facing. This will reduce the need for issue triage and save time.

 - [x] I confirm that I have searched the issue tracker

**Describe the bug**
After a few days of use u tried to open LabNex but it keeps crashing… it loads, i can see the welcome screen with the buttons for my repositories, issues etc… appear for a split second. Then i see my profile picture loading in thi top right corner and then it crashes.

**To Reproduce**
Use LabNex at leust once, and open it again.

**Expected behavior**
Should not crash 👯

**Logs**
Can't use Logcat unfortunately :/

**Versions (please complete the following information)**
 - LabNex:  
 - Android: 11

**Mode of installation**
 - [ ] Google Play Store
 - [x] F-droid
 - [ ] APK
 - [ ] Built from source

**Comment by licaon-kter** [comment] 2024-10-06 09:40
Why can't you use logcat?

**Comment by Dacid99** [comment] 2024-10-06 12:34
I have the same issue: after logging in and closing the app, reopening leads to a crash.
Im on android 12.1 and installing from fdroid.
These are the logs:

FATAL EXCEPTION: main
Process: com.labnex.app, PID: 16216
java.lang.IllegalStateException: Fragment HomeFragment{19e0f8e} (2e1a4f9d-034c-421a-8773-94a6a654f70b) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:977)
	at com.labnex.app.fragments.HomeFragment$2.onResponse(HomeFragment.java:225)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by licaon-kter** [comment] 2024-10-06 12:52
Maybe fixed already in https://github.com/labnex/LabNex/blob/ad4ab5fcf3fbb77969a1201c7f9e48043a4ad54a/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Flabnex%2Fapp%2Factivities%2FMainActivity.java for the next version

**Comment by mmarif4u** [comment] 2024-10-06 13:56
@Cwpute, thanks for the report, and @Dacid99, thanks for adding the log.

From my testing, I didn’t encounter the crash. However, I’ve made a change to the line in question. Could you please test the attached debug APK? (Uninstall the F-Droid version first)

[LabNex-debug.zip](https://github.com/user-attachments/files/17269589/LabNex-debug.zip)

**Comment by Dacid99** [comment] 2024-10-06 17:12
That doesnt solve it unfortunately.
Heres the log to the crash:


FATAL EXCEPTION: main
Process: com.labnex.app, PID: 11214
java.lang.AssertionError
	at com.labnex.app.fragments.HomeFragment$2.onResponse(HomeFragment.java:225)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by mmarif4u** [comment] 2024-10-06 17:34
Can you provide more information, like what version of GitLab you are using? Is it self-hosted?

**Comment by Dacid99** [comment] 2024-10-06 17:44
I just use the public gitlab at gitlab.com

**Comment by mmarif4u** [comment] 2024-10-06 18:09
Ok, thanks. It is most likely an issue with the user details endpoint. I will look into it soon.

**Comment by mmarif4u** [comment] 2024-10-06 19:11
@Cwpute @Dacid99 
Just wondering if you have created the token with the required scopes?

Check this image—if not all, at least these should be selected for the app to work.

![Screenshot_20241007_000831](https://github.com/user-attachments/assets/8ee670a2-7fe1-4b82-b482-d60fdb4bd8d8)

**Comment by Dacid99** [comment] 2024-10-06 19:59
I have tried again with all api fields checked as shown but it crashed again.


Thanks a lot for your effort to get to the bottom of this!



FATAL EXCEPTION: main
Process: com.labnex.app, PID: 23451
java.lang.AssertionError
	at com.labnex.app.fragments.HomeFragment$2.onResponse(HomeFragment.java:225)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by mmarif4u** [comment] 2024-10-06 20:07
No problem. Try the F-droid version with the new token and see if it still crashes.

**Comment by Dacid99** [comment] 2024-10-06 20:24
I tried but got another crash.
I think this is the original error again:

FATAL EXCEPTION: main
Process: com.labnex.app, PID: 12584
java.lang.IllegalStateException: Fragment HomeFragment{6e971c7} (4432ec65-4828-451f-aa42-b5b8cca19d1b) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:977)
	at com.labnex.app.fragments.HomeFragment$2.onResponse(HomeFragment.java:225)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by Cwpute** [comment] 2024-10-07 07:55
@mmarif4u i had activated all scopes except for `ai_features`.
@licaon-kter actually that was with my previous laptop, an old 32bit tablet-pc with al kinds of problems. i shall try again with my nev one, and there really is a need for it.

**Comment by mmarif4u** [comment] 2024-10-07 14:30
As the issue is not reproducible on my side, it's hard to debug and fix. I am trying to identify any possible cause that might crash the app.

Please check this APK and let me know.
[LabNex-debug.zip](https://github.com/user-attachments/files/17280161/LabNex-debug.zip)

**Comment by Dacid99** [comment] 2024-10-12 08:34
Sorry for the late reply. I tested the new debug apk. Before it crashes I can see the home screen and then the exception occurs. 
At least the error message is shorter now :sweat_smile:  :
 FATAL EXCEPTION: main
Process: com.labnex.app, PID: 23876
java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView com.labnex.app.databinding.FragmentHomeBinding.welcomeTextHi' on a null object reference
	at com.labnex.app.fragments.HomeFragment$2.onResponse(HomeFragment.java:231)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by Dacid99** [comment] 2024-10-12 08:45
I also tested it on a android 13 device and there it works just fine.

**Comment by mmarif4u** [comment] 2024-10-12 10:34
Thanks. I mostly use the Android 13 emulator for testing, but I will check on Android 12 and 11 to see if I can reproduce the issue and fix the bug along the way.

**Closed** 2024-10-18 06:13 UTC
Labels: 🐛 Bug
